apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-depoyment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscaleweb-deployment
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 10