apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: web-deployment 
  template:
    metadata:
      labels:
        run: web-deployment
    spec:
      containers:
      - name: web-deployment
        image: mcr.microsoft.com/azuredocs/aci-helloworld
        ports:
        - containerPort: 80
